# default
logger_level: info
labels: null
validate_label: null
sort_labels: true
label_flags: null
flags: null
file_search: null
keep_prev: false

# main
inference_dock:
  show: true
  closable: true
  movable: true
  floatable: true
property_dock:
  show: false
  closable: true
  movable: true
  floatable: true
defect_dock:
  show: false
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false
epsilon: 10.0
shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  analysis: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  select_all_file: Ctrl+A
  open_next: D
  open_prev: A
  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  left_rotate: Ctrl+Shift+L
  right_rotate: Ctrl+Shift+R
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F